### ISSUE TITLE
work space number is not visible in ubuntu

### ISSUE THREAD

**Issue by Ashutosh-Tripathy** [unix121/i3wm-themer#101]
Using ubuntu 18.
i3wm-theme repo status: last commit fde5acdfddc2bbc395223804717ccd83dc8dce42 
Author: JohannesPertl <45853628+JohannesPertl@users.noreply.github.com>
Date:   Thu Apr 16 01:21:40 2020 +0200

Work space number is not visible.

![image](https://user-images.githubusercontent.com/12702948/79628761-8a47e600-8161-11ea-855c-a6654044b2c7.png)

**Comment by romankrru** [comment]
Same issue.

For now fixed by replacing following lines in `~/.config/i3/config`:
```
gaps inner 10
gaps outer -4
```
with
```
gaps top 25
gaps inner 10
```

**Comment by Ashutosh-Tripathy** [comment]
Did not work in my case.

**Comment by floppydisken** [comment]
I'm having the same problem. Able to see the numbers without `smart_gaps on`

**Comment by floppydisken** [comment]
After having fiddled around abit, I figured out what was causing the problem. 
In you Polybar config located in `$HOME/.config/polybar/config` comment out or remove 
```markdown 
;wm-restack = i3
;override-redirect = true
```
Your bar should no longer be overlapped by windows.
