### ISSUE TITLE
How to change transparency of unfocused windows?

### ISSUE THREAD

**Issue by joshmyersdean** [unix121/i3wm-themer#103]
I'm not seeing an option to do so in the i3 config but I may just be overlooking it. Thank you for making this!

**Comment by unix121** [comment]
Hello sir, I am not that sure if you can do this directly on i3. What I would try is to change it through the compositor. You can for example, if you are using compton set it from your compton config.

**Comment by joshmyersdean** [comment]
Thank you, you are correct! closing issue
