### ISSUE TITLE
wallpaper isn't rendered properly, polybar is also being overlapped by the windows

### ISSUE THREAD

**Issue by marzdgzmn** [unix121/i3wm-themer#105]
System Info:
```
Description:	Manjaro Linux
Release:	19.0.2

```

When applying a theme via: ` python i3wm-themer.py --config config.yaml --load themes/001.json`. The wallpaper doesn't seem to be rendered properly. Is it like zoomed in or stretched.
![2020-05-23-164415_1918x1077_scrot](https://user-images.githubusercontent.com/26958260/82726132-b46a6600-9d14-11ea-8680-c36149ea6e80.png)

Also, I'm not quire sure if it is by design, but the polybar is being overlapped by the windows.
![2020-05-23-164426_1918x1079_scrot](https://user-images.githubusercontent.com/26958260/82726128-b2a0a280-9d14-11ea-8e0d-60a5308715bb.png)

Lastly, cursor always seems to be loading displaying a circular icon.

**Comment by hinosxz** [comment]
I just installed on Ubuntu 20.04 and am facing the same issue with the status bar overlap. Everything else works great though :man_shrugging:

**Comment by marzdgzmn** [comment]
I'm pretty new this, but I figured out that I had to use the nitrogen UI to set the wallpaper properly on my laptop screen as well as my second external monitor.

However, I still can't figure out the overlapping issue and the cursor that always seems to be loading after logging in.

**Comment by HiImJulien** [comment]
@marzdgzmn Edit the file '~/.config/polybar

**Comment by marzdgzmn** [comment]
Just updated my manjaro system, if anyone stumbles on the same problem:

```
polybar: error while loading shared libraries: libjsoncpp.so.21: cannot open shared object file: No such file or director
```
I had to rebuildl the polybar-git so it links to the new .so file.

**Comment by unix121** [comment]
I am closing this issue since I see it's been resolved months ago, if anything similar comes up please re-open it.
