### ISSUE TITLE
is this the finished product ?

### ISSUE THREAD

**Issue by srajith** [unix121/i3wm-themer#108]
i want the top bar to appear even when im having windows open ?

![Screenshot from 2020-06-11 09-17-06](https://user-images.githubusercontent.com/40263349/84342982-97fb7400-abc4-11ea-8f7b-6e4f440c985b.png)
![Screenshot from 2020-06-11 09-17-00](https://user-images.githubusercontent.com/40263349/84342986-9b8efb00-abc4-11ea-9df4-191c1f7d8e7d.png)

**Comment by unix121** [comment]
Hello sir,

You could try the solution provided here: https://github.com/unix121/i3wm-themer/issues/105

**Comment by srajith** [comment]
hey thanks it fixed it ! how can i display like the ram and cpu

**Comment by unix121** [comment]
You should probably check out the [Polybar wiki](https://github.com/polybar/polybar/wiki) sir.
