### ISSUE TITLE
Use PPA's to install dependencies on Ubuntu installation script

### ISSUE THREAD

**Issue by diegosanchezp** [unix121/i3wm-themer#111]
Reading the source code of the installation script for Ubuntu `install_ubuntu.sh` I see that the following dependencies and its dependents are build from source or compiled

- i3 gaps
- Polybar

Maybe the code can be refactored to use PPA's?

I have personally use this [PPA](https://launchpad.net/~kgilmer/+archive/ubuntu/speed-ricer) to install some of those dependencies, which is maintained by the [regolith-linux](https://github.com/regolith-linux/speed-ricer) team 

Hope this helps to avoid less bugs like those mentioned in #107 ?

**Comment by unix121** [comment]
Hello sir,

I have personally never used the PPA directly (I've used i3 on Ubuntu like only once in the past), so I don't know if there would be any major difference. But in general it's a good idea to use it to avoid dependency issues. Would you mind creating a PR with the suggested changes?

**Comment by diegosanchezp** [comment]
Hi!
Yeah I would have no problem to create a PR, give me a week to test with those changes, if there is no Pull Request means that my experiment failed.
