### ISSUE TITLE
I3 config file error

### ISSUE THREAD

**Issue by ArcadeJanitor** [unix121/i3wm-themer#113]
All scripts and setup has worked perfectly for me many time on Manjaro, having recently moved to Arch, i went to install these themes again. 

after running 
`python i3wm-themer.py --config config.yaml --load themes/002json` 
The script runs, you can see i3 reload and then you get kicked to greeter again. 
Attempting to log in to the greeter shows a successful log in, i3 crash and kicked to greeter again. 

I solved it by logging into another tty and
`rm ~/.config/i3/config`
Go back to greeter and log in. 
I3 acts brand new and generates a new config file.

**Comment by unix121** [comment]
Hello sir,

I haven't tried the installer in pure Arch in nearly 2 years, so I cannot check what could be wrong. If you happen to find the answer please let me know and we can fix it. I will mark this as "Help Wanted" in case anyone wants to dig into this.

**Comment by ArcadeJanitor** [comment]
I am currently debugging everything. but its a long and slow process. i happen to know that the script works on a clean manjaro i3 build as i tested that again but no luck with arch, will let you know how i get on.

**Comment by ArcadeJanitor** [comment]
Okay so a little update, i have manually moved all the values from your .json files into my config files and everything works. I have had a look through your python and i don't think i missed anything so may just be an issue on my end. in case i missed anything, i have copied the files from /defults to replace my configs, changed them with the values for a json files. added `exec always xrdb ~/.Xresources` to i3 and manually configured picom (just set the image). as of right now everything is working and loading correctly, no issues.
