### ISSUE TITLE
Mistake in your git Why? section

### ISSUE THREAD

**Issue by mrgatesjunior** [unix121/i3wm-themer#121]
The line:

Satan > Jesus should be the following:

Jesus much > Satan

**Comment by unix121** [comment]
Hello sir, I sometimes wonder if people actually take this seriously (I mean the `Satan > Jesus` part of the README).

**Comment by unix121** [comment]
Just to clarify, in case people wonder, cloning this repository `will not summon Satan or any other evil force on your computer and you will not be cursed for 1000 years`.

**Comment by mrgatesjunior** [comment]
It is literal in the Why as it is.  If you don’t mean it that way then I would put the full sentence about cloning it there instead.  As it is stated it appears your someone who is saying that Satan is greater than Jesus.

Just my thoughts.
