### ISSUE TITLE
polybar not fully showing, it just shows the workspace number and time. (like its cut off or something)

### ISSUE THREAD

**Issue by ins0mniacdude** [unix121/i3wm-themer#123]
https://imgur.com/a/xUnNmLo

**Comment by ins0mniacdude** [comment]
[https://imgur.com/a/xUnNmLo](url)

**Comment by unix121** [comment]
Hello @ins0mniacdude,

I have no idea what's going on there. Did you manage to find a solution? If yes, then please share it in case anyone has the same issue again.

**Comment by ins0mniacdude** [comment]
> 
> 
> Hello @ins0mniacdude,
> 
> I have no idea what's going on there. Did you manage to find a solution? If yes, then please share it in case anyone has the same issue again.

**Comment by ins0mniacdude** [comment]
no i did not find a solution sadly.

**Comment by JsThiago** [comment]
Same. Looks like mate-power-manager isn't working as expected.
