### ISSUE TITLE
Remove rofi theme after uninstallation

### ISSUE THREAD

**Issue by carrotfarmer** [unix121/i3wm-themer#124]
I uninstalled `i3wm-themer` but the rofi theme is still applied. I searched for it in the `~/.config` directory but nothing's listed there. Where can I find the Rofi config/theme so that I can remove it to set it back to the default config/theme.

I'm on Arch btw.

Thanks in advance.

**Comment by unix121** [comment]
Hello @carrotfarmer,

You can look into the `~/.Xresources` file, there should be a few options for `rofi.*`. Just remove those and run `xrdb ~/.Xresources` and the theme should be removed.

**Comment by carrotfarmer** [comment]
Ah, yes thank you!
