### ISSUE TITLE
Polybar overlapping on top of i3 windows

### ISSUE THREAD

**Issue by neza8a** [unix121/i3wm-themer#14]
I'm trying to get my polybar look like yours in the Minimal theme, but when I open an application, the top part of it is hidden under the polybar.
In my config, I have:
`override-redirect = true`
and disabled wm-restack for i3, because otherwise i3 windows overlap on top of the polybar instead.

**Comment by jaydh** [comment]
Comments in [here](https://github.com/jaagr/polybar/issues/293) suggest you need to have wm-restack enable for override-redirect to do anything.

Can you post your i3 config?

Is this happening with both tiling windows and floating windows?

This is also not an issue with i3-themer and probably not the best place to ask about general i3/polybar questions.

**Comment by unix121** [comment]
The answer given by @jaydh should work for you. 
In any case, I'm closing this issue because it's either a polybar or i3 issue.
