### ISSUE TITLE
Theme fails to load on login

### ISSUE THREAD

**Issue by DroidFreak32** [unix121/i3wm-themer#17]
First of all I am in love with this.
There's one problem I've been experiencing lately.
After I set the theme, logout of the session and re-login, the theme fails to load.
I have to run the script again to make it load.
the .xresources file and the i3 config are not even changed after re-login. And if i try reloading i3, theres no change either.
I have to always run the script at startup to get back the theme. 

Environment:
manjaro i3 edition
secondary cinnamon DE
linux 4.15-manjaro

**Comment by unix121** [comment]
Hello sir, I have responded to you at the Manjaro forums, but in any case here is my response:

Hey man, that's actually really really odd.

If you could please check your current `~/.i3/config`, `~/.Xresources`, `~/.extend.Xresources` and lastly `~/.config/polybar/config` and paste-bin them if you could so I can take a look on them.

(Reply either here or on the forums, I'll check it out anywhere)

**Comment by DroidFreak32** [comment]
I was able to get it working by replacing my xresources with yours.
