### ISSUE TITLE
Xrandr miss behaving

### ISSUE THREAD

**Issue by Prathik-Jain** [unix121/i3wm-themer#19]
I tried one of your themes .. and I am not able to figure out what your scripts changed.But it has got my xrandr in trouble for dual screen with different res. Please let me know what u change in the display settings

**Comment by unix121** [comment]
Hello sir, this is not an issue with my script , more like an issue with Xrandr. If you wanna set your monitors you could always try "arandr" and then set your monitors as you like. After that save the output to an sh script and add it in your i3 configuration. The script doesn't even mess with your monitor configs, if something happened it has to be unrelated to the script.

**Comment by Prathik-Jain** [comment]
Okay thanks.. I dont know whats wrong. Anyways I'll figure it out. 
Thank you.

**Comment by unix121** [comment]
Hello sir,

The whole repository has been reworked, so I'm closing this issue for now. In case you meet any new issues then please open a new `Issue` thread that is more up-to-date.
