### ISSUE TITLE
Errors when trying to install or retheme files

### ISSUE THREAD

**Issue by jhthenerd** [unix121/i3wm-themer#21]
When I try to install files, the program returns that the folder was located, but failed to install the new file:

```
python i3wm-themer.py --config config.yaml --install defaults/
('\x1b[0;34;40m [>] ', 'Located the config file', '\x1b[0m')
('\x1b[0;34;40m [>] ', 'Intalling the files from defaults/file.', '\x1b[0m')
('\x1b[0;34;40m [>] ', 'Located the folder.', '\x1b[0m')
('\x1b[0;32;40m [>] \x1b[0m', 'Located /home/jason/.config/i3/configfile!')
('\x1b[0;31;40m [x] \x1b[0m', 'Failed to install the new file!')
('\x1b[0;31;40m [x] \x1b[0m', 'Failed!')
('\x1b[0;32;40m [>] \x1b[0m', 'Located /home/jason/.config/polybar/configfile!')
('\x1b[0;31;40m [x] \x1b[0m', 'Failed to install the new file!')
('\x1b[0;31;40m [x] \x1b[0m', 'Failed!')
('\x1b[0;32;40m [>] \x1b[0m', 'Located /home/jason/.Xresourcesfile!')
('\x1b[0;31;40m [x] \x1b[0m', 'Failed to install the new file!')
('\x1b[0;31;40m [x] \x1b[0m', 'Failed!')
('\x1b[0;34;40m [>] ', 'Refreshing i3 and xrdb and setting wallpaper', '\x1b[0m')
('\x1b[0;32;40m [>] \x1b[0m', 'Done!')
```

Polybar is also not loading at all, but rofi is working fine. I am using Ubuntu 17.10.

**Comment by jhthenerd** [comment]
Ok, polybar wasn't loading because the shebang line was
`#!/bin/env`
instead of
`#!/usr/bin/env`

the errors when installing lines in files still occur, and i noticed the wallpaper resets after a relog.

**Comment by unix121** [comment]
Hello sir,

I'm not 100% sure about what is going on here. At this point the script is supposed to just clean copy/paste every file from the defaults/ folder into the right place (You can also do it by hand).

The errors above mean that python's 'copyfile' function fails and I'm not sure why. Just to be sure I would take a look at the permissions for those files in case you don't have the right to modify them.

**Comment by Fibrasek** [comment]
@unix121 thanks for the response! I'll try to fix once I have a break from work (if someone else dont fix it first haha)

**Comment by unix121** [comment]
@Fibrasek I'll attempt to fix it as well, once I find the free time to do so. But any help is always welcome :)
