### ISSUE TITLE
Problem installing default files

### ISSUE THREAD

**Issue by Fibrasek** [unix121/i3wm-themer#22]
First of all, thanks for the project!

While trying to install the defaults, I keep running on this problems:
```
'\x1b[0;34;40m [>] ', 'Located the config file', '\x1b[0m')
('\x1b[0;34;40m [>] ', 'Intalling the files from defaults/file.', '\x1b[0m')
('\x1b[0;34;40m [>] ', 'Located the folder.', '\x1b[0m')
('\x1b[0;32;40m [>] \x1b[0m', 'Located /home/fibrasek/.config/.i3/configfile!')
('\x1b[0;31;40m [x] \x1b[0m', 'Failed to install the new file!')
('\x1b[0;31;40m [x] \x1b[0m', 'Failed!')
('\x1b[0;32;40m [>] \x1b[0m', 'Located /home/fibrasek/.config/polybar/configfile!')
('\x1b[0;31;40m [x] \x1b[0m', 'Failed to install the new file!')
('\x1b[0;31;40m [x] \x1b[0m', 'Failed!')
('\x1b[0;32;40m [>] \x1b[0m', 'Located /home/fibrasek/.Xresourcesfile!')
('\x1b[0;31;40m [x] \x1b[0m', 'Failed to install the new file!')
('\x1b[0;31;40m [x] \x1b[0m', 'Failed!')
('\x1b[0;34;40m [>] ', 'Refreshing i3 and xrdb and setting wallpaper', '\x1b[0m')
('\x1b[0;32;40m [>] \x1b[0m', 'Done!')
```

Already checked the permission on the files, and they are fine. Can this be related to `python` itself? I am not a `python` developer, so I don't know the quirks of the language.

**Comment by unix121** [comment]
Hi sir,

I'm gonna investigate this issue the moment I find some time. For now I just recommend that you just copy-paste the files yourself (it's basically what the script does at this point).

Also there is an <a href="https://github.com/unix121/i3wm-themer/issues/21">open issue</a> with exactly the same thing, so I suggest you subscribe to that and keep up with the updates there. For now I am closing this once it's exactly the same issue as the one mentioned above. :)
