### ISSUE TITLE
polybar-git does not create a config dir

### ISSUE THREAD

**Issue by raghuvanshy** [unix121/i3wm-themer#26]
after installing polybar-git from the arch user repository I see that it has created an executable file ~/.config/polybar there is no folder at that location and thus im unable to copy the scripts as required by the readme.
Any suggestions regarding this?

**Comment by unix121** [comment]
Well generally, you either <a href="https://github.com/jaagr/polybar/wiki#where-to-start">read the first paragraph of the Polybar documentation</a> or you just `touch ~/.config/polybar/config` and then run the script. I was thinking if I should force-created via the script (check if it's there and if not I create it no matter what) but I need to kinda test it for a while.

**Comment by jamesshane** [comment]
I did 

`install -Dm644 /usr/share/doc/polybar/config $HOME/.config/polybar/config`
followed by
`polybar example`

to set a good base config

**Comment by raghuvanshy** [comment]
command I run:

`install -Dm644 /usr/share/doc/polybar/config $HOME/.config/polybar/config`

the error message:

`install: failed to access '/home/coderiot/.config/polybar/config': Not a directory`

Im running Arch Linux

**Comment by unix121** [comment]
Just create it man. 

`mkdir ~/.config/polybar/config`

**Comment by leopepe** [comment]
polybar can be found on official pacman repo. You don't need to use AUR aymore.

**Comment by unix121** [comment]
That's something I didn't even know to be honest. I will consider pulling it from there in that case. Thanks for the info :)

**Comment by unix121** [comment]
I am closing this one once there is no follow up. Generally if you follow the instructions for the official Polybar page then no problems should exist: https://github.com/jaagr/polybar
