### ISSUE TITLE
wallpaper

### ISSUE THREAD

**Issue by jamesshane** [unix121/i3wm-themer#29]
I keep losing the wallpaper, any ideas?

**Comment by unix121** [comment]
I think that for now you should just pick it directly through Nitrogen (Or whatever Wallpaper manager you use) until a work around is found. I think that moving the wallpapers into /usr/share/backgrounds and setting there from there via Nitrogen might be a descent solution.

**Comment by unix121** [comment]
I'm closing this one, considering that you are the one who made this fix :P
