### ISSUE TITLE
I3 config file has some errors.

### ISSUE THREAD

**Issue by yinyizhixian** [unix121/i3wm-themer#3]
I have executed `./apply_theme.sh -t Minimal` and it's successd.
What I need do additional ? 
I use Fedora 25.
The themes is so nice.

>ERROR: CONFIG: Expected one of these tokens: <word>
ERROR: CONFIG: (in file /home/caiyuyu/.config/i3/config)
ERROR: CONFIG: Line 328: client.focused_inactive					
ERROR: CONFIG: Line 329: client.urgent						
ERROR: CONFIG: Line 330: client.placeholder					
ERROR: CONFIG:           ^^^^^^^^^^^^^^^^^^^^^^^
ERROR: CONFIG: Line 331: 
ERROR: CONFIG: Line 332: 
ERROR: CONFIG: Expected one of these tokens: <word>
ERROR: CONFIG: (in file /home/caiyuyu/.config/i3/config)
ERROR: CONFIG: Line 329: client.urgent						
ERROR: CONFIG: Line 330: client.placeholder					
ERROR: CONFIG: Line 331: 
ERROR: CONFIG:           
ERROR: CONFIG: Line 332: 
ERROR: CONFIG: Line 333: #############################
ERROR: CONFIG: Expected one of these tokens: <end>, '#', 'set', 'set_from_resource', 'bindsym', 'bindcode', 'bind', 'bar', 'font', 'mode', 'floating_minimum_size', 'floating_maximum_size', 'floating_modifier', 'default_orientation', 'workspace_layout', 'new_window', 'new_float', 'hide_edge_borders', 'for_window', 'assign', 'no_focus', 'focus_follows_mouse', 'mouse_warping', 'force_focus_wrapping', 'force_xinerama', 'force-xinerama', 'workspace_auto_back_and_forth', 'fake_outputs', 'fake-outputs', 'force_display_urgency_hint', 'focus_on_window_activation', 'show_marks', 'workspace', 'ipc_socket', 'ipc-socket', 'restart_state', 'popup_during_fullscreen', 'exec_always', 'exec', 'client.background', 'client.focused_inactive', 'client.focused', 'client.unfocused', 'client.urgent', 'client.placeholder'
ERROR: CONFIG: (in file /home/caiyuyu/.config/i3/config)
ERROR: CONFIG: Line 337: 
ERROR: CONFIG: Line 338: # Set inner/outer gaps
ERROR: CONFIG: Line 339: gaps inner 8
ERROR: CONFIG:           ^^^^^^^^^^^^
ERROR: CONFIG: Line 340: gaps outer -4
ERROR: CONFIG: Line 341: 
ERROR: CONFIG: Expected one of these tokens: <end>, '#', 'set', 'set_from_resource', 'bindsym', 'bindcode', 'bind', 'bar', 'font', 'mode', 'floating_minimum_size', 'floating_maximum_size', 'floating_modifier', 'default_orientation', 'workspace_layout', 'new_window', 'new_float', 'hide_edge_borders', 'for_window', 'assign', 'no_focus', 'focus_follows_mouse', 'mouse_warping', 'force_focus_wrapping', 'force_xinerama', 'force-xinerama', 'workspace_auto_back_and_forth', 'fake_outputs', 'fake-outputs', 'force_display_urgency_hint', 'focus_on_window_activation', 'show_marks', 'workspace', 'ipc_socket', 'ipc-socket', 'restart_state', 'popup_during_fullscreen', 'exec_always', 'exec', 'client.background', 'client.focused_inactive', 'client.focused', 'client.unfocused', 'client.urgent', 'client.placeholder'
ERROR: CONFIG: (in file /home/caiyuyu/.config/i3/config)
ERROR: CONFIG: Line 338: # Set inner/outer gaps
ERROR: CONFIG: Line 339: gaps inner 8
ERROR: CONFIG: Line 340: gaps outer -4
ERROR: CONFIG:           ^^^^^^^^^^^^^
ERROR: CONFIG: Line 341: 
ERROR: CONFIG: Line 342: # Additionally, you can issue commands with the following syntax. This is useful to bind keys to changing the gap size.
ERROR: CONFIG: Expected one of these tokens: <end>, '#', 'set', 'set_from_resource', 'bindsym', 'bindcode', 'bind', 'bar', 'font', 'mode', 'floating_minimum_size', 'floating_maximum_size', 'floating_modifier', 'default_orientation', 'workspace_layout', 'new_window', 'new_float', 'hide_edge_borders', 'for_window', 'assign', 'no_focus', 'focus_follows_mouse', 'mouse_warping', 'force_focus_wrapping', 'force_xinerama', 'force-xinerama', 'workspace_auto_back_and_forth', 'fake_outputs', 'fake-outputs', 'force_display_urgency_hint', 'focus_on_window_activation', 'show_marks', 'workspace', 'ipc_socket', 'ipc-socket', 'restart_state', 'popup_during_fullscreen', 'exec_always', 'exec', 'client.background', 'client.focused_inactive', 'client.focused', 'client.unfocused', 'client.urgent', 'client.placeholder'
ERROR: CONFIG: (in file /home/caiyuyu/.config/i3/config)
ERROR: CONFIG: Line 346: 
ERROR: CONFIG: Line 347: # Smart gaps (gaps used if only more than one container on the workspace)
ERROR: CONFIG: Line 348: smart_gaps on
ERROR: CONFIG:           ^^^^^^^^^^^^^
ERROR: CONFIG: Line 349: 
ERROR: CONFIG: Line 350: # Smart borders (draw borders around container only if it is not the only container on this workspace) 
ERROR: FYI: You are using i3 version 4.13 (2016-11-08)
ERROR: Received ConfigureNotify for unknown window 0x00400000
ERROR: Received ExposeEvent for unknown window 0x00400000
ERROR: Received ConfigureNotify for unknown window 0x00400000
ERROR: Received ExposeEvent for unknown window 0x00400000
ERROR: Received ExposeEvent for unknown window 0x00400000
ERROR: No output found at destination coordinates?
ERROR: No output found at destination coordinates?

**Comment by unix121** [comment]
Hello there,

It seems to me like you have not installed i3-gaps in your system, but I cannot tell for sure. If you backed up your files like I mention in the description then it should be easy to go back to your previous configuration and copy by hand most parts of the configuration in your system. 

I am currently working on a new script that replaces only what's needed to avoid issues like that.

I hope that running :

./apply_theme.sh -t ../backups/{name_of_your_backup}

will fix this.

**Comment by karambaq** [comment]
I have that issue everytime when I starts my system, but when I applying theme again all fine. Except compton and only on Minimal theme.

**Comment by unix121** [comment]
That's rather odd, 

I am working on a fix for those kind of problems. 

Did you manage to get your backup back?

**Comment by yinyizhixian** [comment]
May be the reason I install i3 first ?
I try to remove them and reinstall

**Comment by unix121** [comment]
If you saved the backup then you should be able to find all your backed up files under:

i3wm-themes/backups/

If so, just manually copy them back to their original location, this should get everything back where it was before you do any change.
