### ISSUE TITLE
Theme 004 is missing a lighter color for the focused workspace text

### ISSUE THREAD

**Issue by anon5314** [unix121/i3wm-themer#34]
Hello.

I love your work so much I wanted to make an account to contribute. As mentioned in the title - I was missing a white color for the text of the active workspace. I managed to fix it, though!

In .config/polybar/config - change 
`label-focused-foreground = #1d1e26`
to
`label-focused-foreground = #ffffff`

Thank you for your work, I hope this helps someone!

**Comment by unix121** [comment]
Hello sir,

Help is always welcome, you can fork the project, make the changes and then create a Pull Request (so that your contribution is visible to others if you may). I will merge the pull request as soon as I see it :)

**Comment by unix121** [comment]
I'm closing this (for now), any other improvement you want to make you can always create a new Pull Request and I'll check it out.
