### ISSUE TITLE
sudo pip / Arch

### ISSUE THREAD

**Issue by adoxography** [unix121/i3wm-themer#38]
On line 14 of the [Arch install script](https://github.com/unix121/i3wm-themer/blob/master/install_arch.sh), the Python dependencies get installed globally through pip. However, from past experience, running `sudo pip` anything can get you into trouble in Arch, because it confuses pacman. From the [Arch wiki](https://wiki.archlinux.org/index.php/python):

> If you must use pip, use a virtual environment or with `pip install --user` to avoid conflicting with packages in `/usr`. It is always preferred to use pacman to install software.

I already had pyyaml installed globally through pacman (`sudo pacman -S python-yaml`), and it worked just fine for me. I think if that's the only Python dependency that is forseen to be used, it makes more sense to just add `python-yaml` to the packages getting installed by pacman on line 10 and skip installing `requirements.txt` altogether; if not, line 14 should probably be `pip install --user -r requirements.txt`.

**Comment by adoxography** [comment]
I'd be happy to -- I just wanted to get a sense of which route would make most sense for the project. All else being equal, my leaning would be to get pacman to install `pyyaml`, but that has the potential to break things if you guys add an extra Python dependency and forget that the Arch installation script is ignoring `requirements.txt`. Do you have a leaning one way or the other?

**Comment by unix121** [comment]
To be honest, I think I would prefer to get it done through pacman. There is nothing to lose, we can try it and get enough feedback from people, worst case it just gets reverted back, but it's worth trying out.

**Comment by unix121** [comment]
I'm closing this (at least for now).
