### ISSUE TITLE
Icons stopped showing in terminal after install

### ISSUE THREAD

**Issue by mrsorensen** [unix121/i3wm-themer#48]
Just did a full reinstall of my system. Before I installed the i3wmthemer I saw icons for folders in ranger. After the install the icons turned into those squares that indicates missing characters. Any idea why this might be? Thanks for your work!
![2018-10-07-013455_1366x768_scrot](https://user-images.githubusercontent.com/40432547/46576717-46ebb380-c9d1-11e8-8f3a-3252e18967c2.png)

**Comment by unix121** [comment]
Hello sir, sorry for the late response.

This is a kinda "common" issue, most common cause is that the font on the terminal is not configured right. I suppose that you are using `rxvt-unicode` so I suggest you look up how to rightly configure the font you want for that terminal emulator.

Anyways, I hope I was not too late, I'd be glad to know if you solved it or not.

**Comment by jasonwoan** [comment]
I came across this issue with `rxvt-unicode` and a fresh install of `i3wm-themer`. I ended up downloading the [patched powerline fonts](https://github.com/powerline/fonts) and edit `~/.Xresources` with the following:
```
URxvt*font: xft:Source Code Pro for Powerline:size=10, xft:DejaVu Sans Mono for Powerline:size=10
```
The key bit is adding `ft:DejaVu Sans Mono for Powerline:size=10` to get the missing arrow characters since Source Code Pro doesn't appear to have them.

**Comment by mrsorensen** [comment]
Hello! When I change my font to either Deja Vu Sans or the full line jasonwoan commented I get a couple of icons, but not all (see screenshot). I haven't tried very hard to fix this though since icons are not super essential. Thank you both for answering!
![2018-10-11-214417_1366x768_scrot](https://user-images.githubusercontent.com/40432547/46829726-d1039580-cd9e-11e8-8328-31de58065696.png)

**Comment by mrsorensen** [comment]
Update: I got most icons working by going back to the default URxvt font in Manjaro with this line:
`URxvt.font: 9x15,xft:TerminessTTFNerdFontMono`
