### ISSUE TITLE
Changing theme is not possible :(

### ISSUE THREAD

**Issue by Lrtcfr** [unix121/i3wm-themer#6]
I'm using arch linux and I want to install the Forest theme. I followed the instructions and when i3 restart, I have an error. It tell me that client.focused or client.unfocused aren't allowed.

**Comment by karambaq** [comment]
Stavros, can you check your e-mail please?

**Comment by unix121** [comment]
Good evening @Lrtcfr could you please post your i3 configuration file? I might be able to help you.

@karambaq Yes sir, I will reply to your e-mail as soon as possible.

**Comment by sanjeevkpandit** [comment]
@unix121 The above error appears after every login. No change in case after using i3 config from both Ice and Forest themes. But, resumes to work properly after executing `./i3wmthemer -t Ice` from the scripts folder and, the same error appears after log out and log in.
