### ISSUE TITLE
No module named yaml

### ISSUE THREAD

**Issue by gvlasov** [unix121/i3wm-themer#62]
I'm on Debian Sid. Ran 
```
./install_debian.sh
pip install -r requirements.txt
cd src
cp -r ../scripts/* /home/$USER/.config/polybar/
```
When trying to do the next step, it get this:
```
i3wm-themer/src on  master [!]
➜ pwd
/home/suseika/.config/i3/i3wm-themer/src

i3wm-themer/src on  master [!]
➜ python i3wm-themer.py --config config.yaml --install defaults/
Traceback (most recent call last):
  File "i3wm-themer.py", line 8, in <module>
    import yaml
ImportError: No module named yaml

```

but the yaml module from requirements.txt seems to be installed:

```
➜ sudo python3 -m pip install -r ../requirements.txt
Requirement already satisfied: pyyaml==3.13 in /usr/lib/python3/dist-packages (from -r ../requirements.txt (line 1)) (3.13)
```

**Comment by gvlasov** [comment]
I had to do 

```fish
sudo apt install python-yaml
```

for `i3wm-themer.py` to work

**Comment by unix121** [comment]
That's weird, I'll create a Debian VM at some point and test it out, there might be some changes needed in the Debian script.

**Comment by floppydisken** [comment]
I had the same problem. Turned out I was running the wrong python version.

In the first command you're running `python` rather than the more specific `python3`, which is the python version with the dependency installed.

**Comment by unix121** [comment]
Yeap, this should be updated to be always `python3` once it's anyways the current standard. I will probably look into updating the repo sometime soon.

**Comment by floppydisken** [comment]
Honestly, I might as well create the pull request and contribute a little. Seems like such a trivial thing.

**Comment by unix121** [comment]
It would be very helpful if you could do that.

**Comment by unix121** [comment]
Closing this since it's related to #115 .
