### ISSUE TITLE
backup.py should check there are files

### ISSUE THREAD

**Issue by OctopusET** [unix121/i3wm-themer#64]
i was installing this theme with script, but i couldn't notice this thing make a just one backup file, a original config file that i edited is gone forever. it was totally my mistake but i want no one do this dummy thing again. this thing should check there are backup files and if its exist it should make another backup like backup[2]/i3/config etc.... Thanks

**Comment by unix121** [comment]
Hello sir,

I hadn't really thought of that, but a basic check is 100% doable, so it will be added into the TODO list for the future.

**Comment by OctopusET** [comment]
Thank you for reply, im really appreciate you for caring. And, thank you for wonderful theme packages!
