### ISSUE TITLE
Slowed down window opening

### ISSUE THREAD

**Issue by EpipolarWagner** [unix121/i3wm-themer#66]
Hi 
I installed i3wm-themer on ubuntu 16.04, however after installation my workstation seems to betremendously slowed down when opening windows. dmenu_run takes 2 (similar for opening a terminal etc. )seconds to pop up. I am relative clue less what can cause this issue. The issue seems to be indpendet from from the config files (.Xresources (also erased the file), i3/config, polybar/confg) as I am facing the same issue under unity. Do you have any idea what could cause this problem? And / or guide me through a clean uninstall?

Best wishes

**Comment by unix121** [comment]
Hello sir, (sorry for the late response)

I really have no idea what is going on with this, i3 is extremely lightweight so it should not cause problems like that no matter what.

What could possibly be happening (and I cannot confirm it) is that if you are in older hardware then (maybe) my compton config could cause slowdown (generally the more you mess with compton on slower hardware the more it will cause slowdowns). If I were in your shoes I would probably start from the, maybe try turning off all compton shadown etc and go from there.

But still I have my doubts about that, especially cause of the fact that it happens on Unity as well (?).

**Comment by EpipolarWagner** [comment]
Hi,

thanks for the reply. I have not clue what caused the issue. During
execution of your installation script some errors occurred, due to blocked
ppa's by our proxy. Installation continued, without catching these. I guess
that messed up things.

Even after getting a clean install thing stayed laggy. Sadly I had to reset
my complete machine, as I needed to work on it.
It is an performance workstations, so slow hard ware couldn't be the cause.

Best wishes

Am Fr., 22. Feb. 2019, 18:54 hat Stavros Grigoriou <notifications@github.com>
geschrieben:

**Comment by tl-yang** [comment]
I'm having the same issue. Using Ubuntu 16.04.  My guess is because of the font loading? Cause rofi itself doesn't do much when startup? 

Thanks for this great repo by the way

**Comment by crablab** [comment]
Yeah - I have the same issue. I am suspecting it is an issue with the fonts. 

Going to try removing all of them and see if it fixes it

**Comment by unix121** [comment]
Vey helpful of you! Thank you sir!

**Comment by unix121** [comment]
I am closing this since there is no followup and a fix was provided by @crablab .  If anything similar comes up please re-open this issue.
