### ISSUE TITLE
Input method not support?

### ISSUE THREAD

**Issue by CanftIn** [unix121/i3wm-themer#68]
I installed fcitx-im, and whatever i try to open fcitx-configtool and set up language, no tray icon appears and I can't operate to change input method. 
I'v followed wiki to add ```export XMODIFIERS="@im=fcitx"
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"``` in `.xinitrc`file.
Then i try to install ibus, still no tray icon and have no idea to deal. 
But using`ps -e | grep fcitx`,the fcitx is running. I think whether polybar hide the original bar?
Then i try to repeat all these install operating in my another Virtual Machine without `i3wm-themer` , the tray icon works 
![1](https://user-images.githubusercontent.com/26135447/52939084-40694180-339e-11e9-8866-fb8a3b530def.png)
and i can easily change the sunpinyin and keyboard English using `ctrl+space`.
So is there any way to support input method?

**Comment by CanftIn** [comment]
Sorry i don't clearly read the source code and understand how polybar is working.
I find the `tray-position =
;tray-padding =` code in `src/defaults/polybar.template`, and I set code to `tray-position = right
;tray-padding =2` then the tray icon appears like that
![2](https://user-images.githubusercontent.com/26135447/52947353-664c1180-33b1-11e9-9ccc-43043813d195.png)
A helpful issue is that:[https://github.com/jaagr/polybar/issues/643](https://github.com/jaagr/polybar/issues/643)

**Comment by unix121** [comment]
Oh yeah,

maybe I should add a note on the README or a wiki page to show how to restore the system tray. Generally I have it off for aesthetic reasons, I prefer my polybar to be a bit more clean.
