### ISSUE TITLE
Maybe try dual screen?

### ISSUE THREAD

**Issue by CanftIn** [unix121/i3wm-themer#71]
I add a old screen with display resolution(1280 * 1024) by HDMI of laptop. The laptop's screen is 1920 * 1080, the layout is that:
![1](https://user-images.githubusercontent.com/26135447/53645844-c45fdb00-3c74-11e9-81ba-83861126870d.png)
Adding the config to i3 file:
```
exec --no-startup-id xrandr --output HDMI1 --primary --mode 1280x1024 --pos 0x0 --rotate normal --output VIRTUAL1 --off --output eDP1 --mode 1920x1080 --pos 1280x0 --rotate normal
```
so the vice screen and main screen have their own workspace individually(like that: vice screen at workspace 1 and main screen at workspace 2).
One of my questions is whether i can have the two screens all at one workspace?
Another question is how to let the polybar show on the two screens simultaneously.
![2019-03-01-230608_3200x1080_scrot](https://user-images.githubusercontent.com/26135447/53646623-a4311b80-3c76-11e9-9239-4fd1b41c9f95.png)
That is my screens. Obviously the left screen has no bar.
By the way, the background wallpaper is tiling on two windows rather than tiling on a window one by one. Is any way to fix these?

**Comment by CanftIn** [comment]
I set nitrogen config file to make wallpaper zoom well. Now just the previous two questions.

**Comment by unix121** [comment]
Hello sir! Sorry for the (very) late response.

For your first question I suspect that you mean have for example `Workspace A` to extend from the first monitor to the second. I don't really know if it is possible at all on `i3` , and I haven't really encountered a setup like this in the past so I don't know how to help with that :( 

For the second question - if you want the same exact polybar  (not extend - just duplicate) I think the right way to do this is to copy the configuration for the first bar into a configuration for a second bar (exact same configuration - but set the `monitor` option to the value of the other monitor) and restart the polybar. This should (normally) cause the bar to duplicate into the second monitor.

I would suggest that you take a look at the polybar wiki (https://github.com/polybar/polybar/wiki/Configuration) , might be more enlightening.
