### ISSUE TITLE
Setting themes is not working, wallpapers not working.

### ISSUE THREAD

**Issue by Zephrum** [unix121/i3wm-themer#75]
When I run 
python i3wm-themer.py --config config.yaml --load themes/[theme_id].json
terminal returns "failed to load .json file"
Also as of this moment my wallpaper has not changed during the install process.
I am running MANJARO I3 gaps, and I was successful every step of the way on this install process up until this point. Please advise. Thanx

**Comment by unix121** [comment]
Hello sir,

I was not really able to reproduce this. Could it be that you miss-typed something ? If the theme exists under `themes/` folder, this should not normally happen.

**Comment by unix121** [comment]
Please see #77 .
