### ISSUE TITLE
Change  theme 

### ISSUE THREAD

**Issue by kjhuanhao** [unix121/i3wm-themer#77]
## Change  theme 
The following error occurred when I changed the theme
```
python i3wm-themer.py --config config.yaml --load themes/[006].json
[>] Located the config file
/home/huanhao/Downloads/i3wm-themer-master/src/config.py:14: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  for conf in config:
[x] Failed to locate the json file
```

**Comment by unix121** [comment]
Hello sir, I'm sorry for the late response.

If this is still the case, could you give some more information? Like python version, OS, etc?

If you managed to solve this, could you please share how you did it in case someone encounters it as well?

**Comment by MrIdle** [comment]
Hello,

I' m having the same issue. I'm on Ubuntu 18.04 and my python version is 3.6.3. What other info would be helpful?

**Comment by evergreenexplicit** [comment]
You should not include the square brackets.
`python i3wm-themer.py --config config.yaml --load themes/006.json` 
works just fine

**Comment by unix121** [comment]
@evergreenexplicit You are so right. I didn't even notice that.

**Comment by unix121** [comment]
I am closing this issue, if anything similar come up please re-open it.
