### ISSUE TITLE
Polybar not showing applets

### ISSUE THREAD

**Issue by keddad** [unix121/i3wm-themer#79]
No applets are showing on a polybar. I've fixed this issue by this fix:
https://github.com/polybar/polybar/issues/1355#issuecomment-449723313
So it is probably worth adding to the config in the repo, but I'm not sure, since I don't really know if it doesn't break anything else.

**Comment by unix121** [comment]
Hello sir, sorry for the late response.

If you don't mind, could you please make a PR for this? In case anyone encounters this issue so it can be quick fixed?

**Comment by keddad** [comment]
Opened a PR #83

**Comment by unix121** [comment]
PR is merged, thanks again :)
