### ISSUE TITLE
polybar adn i3 can't detect colors

### ISSUE THREAD

**Issue by canopeerus** [unix121/i3wm-themer#8]
Hi, I just followed your instructions form the readme by first running with the -c arguemtn which successfully added the required stuff to the start of both files. However running the script to set a theme fails and a lot of actions list as failed in the terminal. The rofi colorscheme and gtk theme seem to work fine but polybar,i3 urxvt fail to set new colors. Here's the output on running the script.

[1;1m[1;32m[1;1m[*] i3wmthemer script started[1;0m

[1;1m[1;32m[1;1m[*] You have entered theming mode.[1;0m
	[1;1m[1;32m[1;1m[*] Located the theme directory.[1;0m
	[1;1m[1;32m[1;1m[+][1;0m Fonts are set up successfully
	[1;1m[1;32m[1;1m[+][1;0m GTK Theme migration completed successfully.
	[1;1m[1;32m[1;1m[+][1;0m Icon migration completed successfully.
	[1;1m[1;32m[1;1m[*] Located .extend.Xresources file in theme the directory.[1;0m
	[1;1m[1;32m[1;1m[*] Located ~/.Xresources file.[1;0m
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.background: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.foreground: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.cursorColor: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite URxvt.background .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite URxvt*foreground .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite URxvt*cursorColor .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite URxvt.font .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color0: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color1: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color2: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color3: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color4: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color5: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color6: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color7: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color8: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color9: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color10: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color11: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color12: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color13: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color14: .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite *.color15: .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite rofi.color-enabled:
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite rofi.color-window:
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite rofi.color-normal:
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite rofi.color-active:
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite rofi.color-urgent:
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite rofi.font:
	[1;1m[1;32m[1;1m[*] Finished editing ~/.extend.Xresources file.[1;0m
	[1;1m[1;32m[1;1m[*] Executing 'xrdb ~/.Xresources' command.[1;0m
	[1;1m[1;32m[1;1m[*] Success![1;0m
	[1;1m[1;32m[1;1m[+][1;0m Located .i3/config file in the theme directory.
	[1;1m[1;32m[1;1m[+][1;0m Located ~/.config/i3/config file.
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite new_window .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite new_float .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite new_window .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite client.background .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite client.focused .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite client.unfocused .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite client.focused_inactive .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite client.urgent .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite client.placeholder .
	[1;1m[1;32m[1;1m[+][1;0m Located .config/polybar/config file in the theme directory.
	[1;1m[1;32m[1;1m[+][1;0m Located ~/.config/polybar/config file.
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite bottom .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite height .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite width .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite offset-x .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite offset-y .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite fixed-center .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite line-size .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite line-color .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite border-size .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite border-color .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite padding-left .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite padding-right .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite module-margin-left .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite module-margin-right .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite tray-position .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite tray-padding .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite tray-transparent .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite tray-offset-x .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite tray-offset-y .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite tray-maxsize .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite tray-detached .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite tray-background .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite wm-restack .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite background .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite foreground .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite ;override-redirect
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-unfocused-background .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-unfocused-foreground .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-unfocused-underline .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-focused-background .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-focused-foreground .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-focused-underline .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-mode-background .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-visible-background .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-visible-foreground .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-visible-underline .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-urgent-background .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-urgent-foreground .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite label-urgent-underline .
	[1;1m[1;32m[1;1m[+][1;0m Applied change: Overwrite line-size .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite line-color .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite border-size .
	[1;1m[1;32m[1;1m[-][1;0m Failed to apply change: Overwrite border-color .
	[1;1m[1;32m[1;1m[+][1;0m Located .config/polybar/config file in the theme directory.
	[1;1m[1;32m[1;1m[-][1;0m Failed to locate ~/.dmenurc in your configuration
	[1;1m[1;32m[1;1m[+][1;0m Located .config/compton.config file in the theme directory.
	[1;1m[1;32m[1;1m[-][1;0m Failed to locate ~/.config/compton.conf in your configuration
	[1;1m[1;32m[1;1m[+][1;0m Wallpaper set successfully
	[1;1m[1;32m[1;1m[*] Restarting i3wm...[1;0m
	[1;1m[1;32m[1;1m[*] Success![1;0m
[1;1m[1;32m[1;1m[!][1;0m Almost done, please use your appearance manager to set the wallpaper and GTK/Icon themes

[1;1m[1;32m[1;1m[*] i3wmthemer finished

[1;0m

**Comment by AdrienBenduc** [comment]
Hello canopeerus,
I think I have exactly the same issue. I've just followed the steps one by one (from an ubuntu server 16.04).

**Comment by romulomourao** [comment]
same issue for me

**Comment by durdo** [comment]
Any update on this? I am having the same problem.

**Comment by durdo** [comment]
Any update on this? I am having the same problem.

**Comment by Sudokamikaze** [comment]
Strange, i'm using this on Archlinux, awesome wm and terminal is termite

**Comment by unix121** [comment]
Hello guys and sorry for the very late response, I am extremely busy those past months and didn't have the time to take a look at the problem. 

I know that the script has a few issues but I would still recommend that you install the themes in the manual way (by hand, simple copy-paste) if you are having issues with the script. 

For now, the only thing that I have to say, is that the configuration files must kinda match in "style" with the themes that I provide. For example you must have your .Xresources colours in the " *.colorx: " and not in the " *colorx: " format if you want the script to make changes. Also about the polybar issues, (like everything in the script ) the script only REPLACES existing lines in the configuration files , it does not add new lines when you run it to apply the themes. For example if you are missing the line " wm-restack " , the script will not add it at all. 

After I'm done with my university thesis I will spend the time to rewrite the whole script and make it work every time, but for now I'm too busy and I'm sorry for that.

Have a good time guys,
Stavros

**Comment by unix121** [comment]
Also, forgot to mention that if you wish to use the script you could try to template your configuration files in a way similar to those: https://github.com/unix121/i3wm-themer/tree/master/templated_themes/ , just pick a random theme and try to compare the dotfiles to yours. Once they are templated in a similar way the script should actually  work. But still, as I said I will work on a brand new script after I find the time to.

**Comment by durdo** [comment]
Hello @unix121,

I think you shouldn't close issues you did not solve.

In this issue, for example, I can try to provide a new option in the "i3wmthemer" that copy the theme instead of replacing it. Something along the lines of:

./i3wmthemer -g {THEME}

Once a functionality like this is in place you can truly say that the issue does not exists.

In any case, I'll try to solve my problem locally and once it is working I can pull changes to you branch.

Best regards,
Eduardo.

**Comment by unix121** [comment]
The issue will be re-opened as you requested.

If you find a solution just create a pull request , and I will check it out and probably merge it. 

There is an alternative (not recommended tho) to use the [old script](https://github.com/unix121/i3wm-themer/blob/master/scripts/old_versions/apply_theme.sh) which copies the entire configuration into your system but is not recommended because it will change your keybinding to my and might mess up your system.

But anyways, I'd be glad if you can find the bug on your own and just merge it.

Best regards,
Stavros

**Comment by unix121** [comment]
Hello guys,

The whole repository has been reworked, so I'm closing this issue for now. In case you meet any new issues then please open a new `Issue` thread that is more up-to-date.
