### ISSUE TITLE
After uninstalling cannot exit session with $mod+ctrl+e

### ISSUE THREAD

**Issue by AminTaghikhani** [unix121/i3wm-themer#80]
Hi,
I uninstall i3wm-themer then reboot and log in to default i3.
When I want to exit the i3 session with $mod+ctrl+e, The yellow notification bar show but yes button not displayed. I uninstall i3, i3-wm,... with purge and clear apt cache then reinstall i3. but the problem not solved, can you help me what should I do?

**Comment by unix121** [comment]
Hello sir and sorry for the late response,

I'm not that sure if re-installing i3wm would fix this, once I don't know if it really overrides the current configuration (rebuilds the default i3 configuration file). Did you try simply copying the default config from the defaults?

Based on the [i3 guide](https://i3wm.org/docs/userguide.html) the default is located on `/etc/i3/config`, maybe it's a good place to start.

**Comment by AminTaghikhani** [comment]
Hello sir, Thanks for your response.

Yes, I change the default configuration file, But nothing changed.
I un-install i3 with `--purge` and remove all configuration files, Then re-install and run the i3 installation wizard but nothing changed.
I copy default configuration from websites and your repository but still not working.

I think `i3-nagbar` has a problem.

Kind regards.

**Comment by AminTaghikhani** [comment]
Hello again,

I found the problem. look at this line:
`i3-nagbar -t warning -m  'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'`

I checked my configs again, inside i3 config `i3-nagbar` command I found the problem.
There is no `-B` option in `i3-nagbar`. option for display a button is `-b`.
I have no idea why this line changed.
I change `-B` to `-b` and everything is ok now.

Kind regards.
