### ISSUE TITLE
Issues with i3 after changing theme.

### ISSUE THREAD

**Issue by jiornojiovanni** [unix121/i3wm-themer#87]
I changed i3 theme with the python script, but now every time I login I go back to the login screen (I use light dm). I tried reinstalling everything, and with vanilla i3 it worked, but after applying the theme once again the same problem appears. 

Btw another question (for when I fix this) how I get my terminal (It's the same) to look like yours? Even with the theme on it was very different.

**Comment by unix121** [comment]
Hello sir, sorry for the late response, about the first question, I don't think that I can provide an answer without more information. What I would try to do is enter `tty` from at the login screen, and revert my i3.config file to the old one to get it running again. There is probably something in there that is bugging it, and try to find it after I restore the session. About your second question, could you provide a screenshot so I can have a look? The usual suspects are normally the fonts, I cannot remember exactly what font I use on most screenshots, but it's probably either Iosevka, Monofur or Source Code Pro.

**Comment by jiornojiovanni** [comment]
sorry I already changed my DE, now I use KDE xD

**Comment by unix121** [comment]
Have fun, KDE is awesome ;)
