### ISSUE TITLE
Polybar configs are missing the wireless network icons 

### ISSUE THREAD

**Issue by tum0ur** [unix121/i3wm-themer#9]
Checking through the polybar configs the wireless network stus icons are missing from themes/[THEME ie Sky]/.config/polybar/config 

Would you be able to add them to the config scripts please?

**Comment by unix121** [comment]
Hello, the network status icon in this theme is the standard NetWorkManager icon, this theme uses the system tray instead of a Polybar module. Just right click on your NetWorkManager and change the icon manually.
