### ISSUE TITLE
Thx, Author. Great work. But I have a problem. After I installed i3 on my Ubuntu, I find the polybar is hidded by the application windows. What can I do

### ISSUE THREAD

**Issue by Adnios** [unix121/i3wm-themer#92]
Thx, Author. Great work. But I have a problem. After I installed i3 on my Ubuntu, I find the polybar is hidded by the application windows. What can I do

**Comment by unix121** [comment]
Hello sir, I think there has been a same issue before, could you check this out:
https://github.com/unix121/i3wm-themer/issues/14

**Comment by Adnios** [comment]
Thx, sir. Problem solved.
