### ISSUE TITLE
polybar.py little bug

### ISSUE THREAD

**Issue by dskart** [unix121/i3wm-themer#94]
Hey, I just saw you have an error in your polybar.py file on line 89/90.

this
```python
 FileUtils.replace_line(configuration.polybar_config, 'format-connected-foreground',
                                   'format-connected-foreground = ' + self.format_con_back)
```
should be 
```python
 FileUtils.replace_line(configuration.polybar_config, 'format-connected-foreground',
                                   'format-connected-foreground = ' + self.format_con_fore)
```

:)

**Comment by unix121** [comment]
Hello sir, would you like to make a PR for this?

**Comment by dskart** [comment]
Yes ! I unfortunately don't know the work flow for this. I already have a fork where I changed some stuff for my own set up and don't want to delete that. Can I make a new branch and commit then PR from there? 

Let me know how I should do this

**Comment by unix121** [comment]
Yes sir, you can do it as you like.
