### ISSUE TITLE
Theme 007 has no visual feedback for current workspace

### ISSUE THREAD

**Issue by JohannesPertl** [unix121/i3wm-themer#98]
Unlike the other themes, theme 007 has the same background color on both focused and unfocused in [007.json](https://github.com/unix121/i3wm-themer/blob/master/themes/007.json)

```
    "label-unfocused-background": "#8abeb7",

...

    "label-focused-background": "#8abeb7",
```

**Comment by unix121** [comment]
Hello again, would you like to fix it and open a new PR for it?
